version: '3.8'

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/log:/mosquitto/log/
      - mosquitto_data:/mosquitto/data/
    networks:
      - codan

  sensor-middleware:
    build: ./sensor-middleware
    container_name: sensor-middleware
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mosquitto
    networks:
      - codan
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - sensor-middleware
    networks:
      - codan

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: --config /etc/mongod.conf --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/log:/var/log/mongodb
      - mongo_data:/data/db
    restart: always
    networks:
      - codan


  mongo-middleware:
    build: ./mongo-middleware
    container_name: mongo-middleware
    environment:
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_DB: metrics
    restart: always
    depends_on:
      - mosquitto
      - mongodb
    networks:
      - codan

networks:
  codan:
    name: codan
    driver: bridge

volumes:
  mosquitto_data: { }
  mongo_data: { }
