version: '3.3'

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.log:/var/log/mosquitto/mosquitto.log
      - mosquitto_data:/var/lib/mosquitto

  sensor-middleware:
    build: ./sensor-middleware
    deploy:
      replicas: 4
    depends_on:
      - mosquitto

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sensor-middleware

volumes:
  mosquitto_data: 