version: '3.8'

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/log:/var/log/mosquitto
      - mosquitto_data:/var/lib/mosquitto

  sensor-middleware:
    build: ./sensor-middleware
    container_name: sensor-middleware
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mosquitto
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - sensor-middleware

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: radmin
      MONGO_INITDB_ROOT_PASSWORD: radmin
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/log:/var/log/mongodb
      - mongo_data:/data/db
    restart: always

  mongo-middleware:
    build: ./mongo-middleware
    container_name: mongo-middleware
    environment:
      - MONGO_USER=radmin
      - MONGO_PASSWORD=radmin
      - MONGO_HOST=mongodb
      - MONGO_DB=metrics
    restart: always
    depends_on:
      - mosquitto
      - mongodb

volumes:
  mosquitto_data:
  mongo_data:
    driver: local
