version: '3.3'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/var/lib/mosquitto
      - ./mosquitto.log:/var/log/mosquitto/mosquitto.log
      
  middleware:
    build: ./sensor-middleware
    container_name: sensor-middleware
    ports:
      - "3000:3000"

volumes:
  mosquitto_data: 
