version: '2'
services:
    soap:
        container_name: soap
        build:
            context: .
            dockerfile: Dockerfile
        image: soap:latest
        ports:
            - 8080:8080
        networks:
            - codan
networks:
    spring-cloud-network:
        driver: bridge
